version: '2'
services:
  postgresql:
    image: "postgres:9.4-alpine"
    ports:
      # We'll bind our host's port 5432 to postgres's port 5432, so we can use
      # our database IDEs with it:
      - 5432:5432
    environment:
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: currencybaskets