spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/currencybaskets
        username: postgres
        password: admin
    jpa:
        show-sql: true
        hibernate:
#        TODO remove after prod migration
          ddl-auto: create-drop