spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currencybaskets
    username: postgres
    password: admin
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
application:
  fixer-key: paste-fixer-api-key-here
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://postgresql:5432/currencybaskets
